version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start -- -v ./data/config.xml"
    depends_on:
      - redis
